DTC_FLAGS += -@
dtb-$(CONFIG_ARCH_MEDIATEK) += camera-ap1302-ar0430-dual.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += camera-ap1302-ar0430-single-csi0.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += camera-ap1302-ar0430-single-csi1.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += display-dsi.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += display-hdmi.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += display-headless.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += net-ethernet.dtbo
