DTC_FLAGS += -@
dtb-$(CONFIG_ARCH_MEDIATEK) += camera-ap1302-ar0430-dual.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += camera-ap1302-ar0430-single-csi0.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += camera-ap1302-ar0430-single-csi1.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += gpu-mali.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += net-ethernet.dtbo
dtb-$(CONFIG_ARCH_MEDIATEK) += video.dtbo
